;;; ivy-pass-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ivy-pass.el

(autoload 'ivy-pass "ivy-pass" "\
Select an entry and copy its password to the kill ring." t)
(register-definition-prefixes "ivy-pass" '("ivy-pass-"))

;;; End of scraped data

(provide 'ivy-pass-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ivy-pass-autoloads.el ends here
